from decimal import Decimal
MESSAGES={
"en-NG":{"balance":"Your available balance is {amount}.","transactions":"I found {count} recent transactions.","transfer_confirm":"Please confirm. You are sending {amount} to {name} at {bank}, account ending {ending}.","pending":"That transaction is still pending. Your money is not marked as lost.","successful":"That transaction was successful.","fraud_reported":"Your report has been recorded and a fraud review case has been opened.","support":"A support case has been opened. Reference {ref}.","unknown":"I did not understand that clearly. Please try again."},
"pcm-NG":{"balance":"Money wey dey available for your account na {amount}.","transactions":"I see {count} recent transactions for your account.","transfer_confirm":"Confirm am first. You wan send {amount} give {name} for {bank}, account wey end with {ending}.","pending":"That transaction still dey process. We never mark your money as lost.","successful":"That transaction successful.","fraud_reported":"We don record the report and open fraud review case.","support":"We don open support case for you. Reference na {ref}.","unknown":"I no understand that one well. Abeg try again."},
"yo-NG":{"balance":"Iye owó tó wà fún lílò nínú àkọọ́lẹ̀ rẹ ni {amount}.","transactions":"Mo rí ìdúnàádúrà {count} tó ṣẹ̀ṣẹ̀ wáyé.","transfer_confirm":"Jọ̀wọ́ jẹ́rìí. O fẹ́ fi {amount} ránṣẹ́ sí {name} ní {bank}, àkọọ́lẹ̀ tó parí sí {ending}.","pending":"Ìdúnàádúrà náà ṣì ń ṣiṣẹ́; a kò kà owó rẹ sí pé ó sọnù.","successful":"Ìdúnàádúrà náà ṣàṣeyọrí.","fraud_reported":"A ti gba ìròyìn rẹ, a sì ti ṣí ìwádìí jìbìtì.","support":"A ti ṣí ẹ̀jọ́ ìrànlọ́wọ́. Nọ́mbà ìtọ́kasí ni {ref}.","unknown":"Mi ò lóye rẹ dáadáa. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan síi."},
"ha-NG":{"balance":"Kudin da yake samuwa a asusunka shi ne {amount}.","transactions":"Na gano mu'amaloli {count} na baya-bayan nan.","transfer_confirm":"Da fatan ka tabbatar. Za ka tura {amount} zuwa {name} a {bank}, asusun da ya ƙare da {ending}.","pending":"Har yanzu ana sarrafa wannan mu'amala. Ba a nuna kuɗinka ya ɓace ba.","successful":"Mu'amalar ta yi nasara.","fraud_reported":"Mun karɓi rahoton kuma mun buɗe binciken zamba.","support":"An buɗe buƙatar taimako. Lambar ita ce {ref}.","unknown":"Ban fahimta sosai ba. Da fatan ka sake gwadawa."},
"ig-NG":{"balance":"Ego dị maka iji ugbu a bụ {amount}.","transactions":"Ahụrụ m azụmahịa {count} kacha ọhụrụ.","transfer_confirm":"Biko kwado. Ị na-eziga {amount} nye {name} na {bank}, akaụntụ na-agwụ na {ending}.","pending":"Azụmahịa ahụ ka na-aga n'ihu. Egosibeghị ego gị dị ka efu.","successful":"Azụmahịa ahụ gara nke ọma.","fraud_reported":"Anyị edebanyela akụkọ ahụ ma mepee nyocha aghụghọ.","support":"Anyị emepela arịrịọ enyemaka. Nọmba ntụaka bụ {ref}.","unknown":"Aghọtaghị m nke ahụ nke ọma. Biko nwaa ọzọ."}}
def msg(lang,key,**kwargs): return MESSAGES.get(lang,MESSAGES["en-NG"]).get(key,MESSAGES["en-NG"].get(key,key)).format(**kwargs)
def money(value): return f"₦{Decimal(str(value)):,.2f}"
